source_directories:
    - /mnt/source/
repositories:
    - path: ssh://u408911@u408911.your-storagebox.de:23/home/borg/nas/repo
      label: hetzner

# we disable this to not have to specify all the mounts individually:
one_file_system: false

#   Passphase is set in varibable $BORG_PASSPHRASE
#   encryption_passphrase: "DoNotForgetToChangeYourPassphrase"
compression: zlib
archive_name_format: 'backup-{now}'

exclude_patterns:
  - '*/log/*'
  - '*/logs/*'
  - '*.log'
  - '*/cache/*'
  - '*.cache'

# Exclude directories that contain a CACHEDIR.TAG file. See
# http://www.brynosaurus.com/cachedir/spec.html for details. Defaults
# to false.
exclude_caches: true

# Exclude directories that contain a file with the given filenames.
# Defaults to not set.
exclude_if_present:
  - .nobackup

# what to keep
keep_daily: 1
keep_weekly: 1
keep_monthly: 1

checks:
  - name: repository
    frequency: 2 weeks
  - name: archives
    frequency: always
  - name: extract
    frequency: 2 weeks
  - name: data
    frequency: 1 month

apprise:
    states:
        - start
        - finish
        - fail

    services:
        - url: mailto://192.168.1.33?to=splitbrain@gmail.com&from=borgmatic@69b.place
          label: mail

    start:
        title: "⚙️ Backup nas: started"
        body: Starting backup process.

    finish:
        title: "✅ Backup nas: SUCCESS"
        body: Backups successfully made.

    fail:
        title: "❌ Backup nas: FAILED"
        body: Your backups have failed.

healthchecks:
    ping_url: ${HEALTHCHECKS_PINGURL}
