services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .volumes/data:/traefik
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--serversTransport.insecureSkipVerify=true"
      - "--providers.docker=true"
      - "--providers.docker.network=proxy"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      
      - "--entrypoints.websecure.address=:443" 
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=69b.place"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.69b.place"

      - "--certificatesresolvers.letsencrypt.acme.email=andi@splitbrain.org"
      - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=porkbun"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=162.159.8.140:53,173.245.58.37:53"
     
    environment:
      LEGO_DISABLE_CNAME_SUPPORT: true
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
    
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.69b.place`)
      traefik.http.routers.traefik.service: api@internal

      homepage.group: System
      homepage.name: Traefik
      homepage.description: Reverse Proxy
      homepage.icon: sh-traefik.svg
      homepage.href: https://traefik.69b.place
      homepage.widget.type: traefik
      homepage.widget.url: http://traefik:8080

networks:
  traefik:
    name: traefik
