services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command:
      - "--cleanup"
      - "--remove-volumes"
    environment:
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: watchtower@69b.place
      WATCHTOWER_NOTIFICATION_EMAIL_TO: splitbrain@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: 192.168.1.33
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 25
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: nas
