services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: nas
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - ./volumes/config:/var/syncthing/config
      - /home/andi:/data
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

    networks:
      - traefik

    labels:
      traefik.enable: true
      traefik.http.routers.syncthing.rule: Host(`syncthing.69b.place`)
      traefik.http.services.syncthing.loadbalancer.server.port: 8384

      homepage.group: Tools
      homepage.name: SyncThing
      homepage.description: File Synchronisation
      homepage.icon: sh-syncthing.svg
      homepage.href: https://syncthing.69b.place

networks:
  traefik:
    name: traefik
    external: true

